services:
  car_organizer:
    build: .
    container_name: car_organizer
    environment:
      - TOKEN=${TOKEN}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_HTTP_PORT=${SLACK_HTTP_PORT:-3000}
      - DB_PATH=/archive
    volumes:
      - ./archive:/archive
    ports:
      - "${SLACK_HTTP_PORT:-3000}:3000"
    restart: unless-stopped
